### ISSUE TITLE
OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by jperedadnr** [javafxports/javafxmobile-plugin#36]
When trying to load relatively big images, with 2.0.16:

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.<init>(Unknown Source)
	at java.lang.Error.<init>(Unknown Source)
	at java.lang.VirtualMachineError.<init>(Unknown Source)
	at java.lang.OutOfMemoryError.<init>(Unknown Source)
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at com.sun.prism.impl.BufferUtil.newByteBuffer(Unknown Source)
	at com.sun.prism.es2.ES2Texture.uploadPixels(Unknown Source)
	at com.sun.prism.es2.ES2Texture.create(Unknown Source)
	at com.sun.prism.es2.ES2ResourceFactory.createTexture(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.createTexture(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
	at com.sun.prism.impl.BaseResourceFactory.getCachedTexture(Unknown Source)
	at com.sun.javafx.sg.prism.NGImageView.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGImageView.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
	at com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(Unknown Source)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(Unknown Source)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at com.sun.javafx.tk.RenderJob.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by odbuser2** [comment]
How big?

**Comment by jperedadnr** [comment]
You can try out a regular `ImageView` with a picture.
So far this size 1728x2304 worked, but 2074x2765 failed with the above exception.
