### ISSUE TITLE
README.md missing info about running sdkmanager under Java8

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#41]
Building for android

**Description**
Running the android sdkmanager command in the README.md results in the following when run with Java9 (I assume that's what users of javafxmobile-plugin are likely to have installed by default):

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
```

**Workaround**
Run with Java 8 by running the following (or similar) before the command
`export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/`

**Comment by johanvos** [comment]
fixed in README -- thanks!
