### ISSUE TITLE
gradle androidInstall fails on simple application

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#42]
org.javafxports:jfxmobile-plugin:2.0.16

**Description**
Running gradle androidInstall results in the following error on a simple app (works fine on desktop and iOS).  The latest Android Studio is installed and the line from the README.md has been executed successfully.

```
WARNING: platform-tools package is not installed.
:cleanAndroid
:validateManifest
:collectMultiDexComponents
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileAndroidJava NO-SOURCE
:processAndroidResources NO-SOURCE
:androidClasses UP-TO-DATE
:copyClassesForDesugar
Mar 19, 2018 01:01:01 PM org.javafxports.retrobuffer.Main main
SEVERE: Failed to run Retrobuffer
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.javafxports.retrobuffer.ClassAnalyzer.analyze(ClassAnalyzer.java:48)
	at org.javafxports.retrobuffer.Retrobuffer$1.visitClass(Retrobuffer.java:59)
	at org.javafxports.retrobuffer.ClasspathVisitor.visitFile(ClasspathVisitor.java:59)
	at org.javafxports.retrobuffer.ClasspathVisitor.visitFile(ClasspathVisitor.java:41)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2713)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2785)
	at org.javafxports.retrobuffer.Retrobuffer.run(Retrobuffer.java:56)
	at org.javafxports.retrobuffer.Main.main(Main.java:45)

:applyRetrobuffer FAILED
```

**Comment by tiainen** [comment]
This exception means there's still at least one class on the classpath that has been compiled with java 9 or higher as the target. There's already an issue for improving the error message by printing the affected class: https://github.com/javafxports/javafxmobile-plugin/issues/32

**Comment by odbuser2** [comment]
Yes, that was the case.  Thanks.
