### ISSUE TITLE
launchIOSDevice : Failure when device is locked occurs at the end of the build

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#47]
Is it possible to check if the device is locked before building instead of waiting until the end?  This is wasting a lot of developer time.
```
ERROR! java.lang.RuntimeException: Launch failed: Locked java.lang.RuntimeException: Launch failed: Locked         
        at com.gluonhq.gvmbuild.DeviceIO.sendReceivePacket(DeviceIO.java:172)   
        at com.gluonhq.gvmbuild.DeviceIO.rerouteIO(DeviceIO.java:65) 
        at com.gluonhq.gvmbuild.BosonAppBuilder$3.run(BosonAppBuilder.java:1232)
```

**Comment by johanvos** [comment]
At the very least, we should show a warning, wait a bit, try again.

**Comment by johanvos** [comment]
should be fixed with 2.0.19
