### ISSUE TITLE
Generating large dex fails with: "main dex capacity exceeded"

### ISSUE THREAD

**Issue by tiainen** [javafxports/javafxmobile-plugin#5]
When generating a build for android with many classes, dex compilation fails with the following Exception:
```
com.android.dex.DexException: Too many classes in --main-dex-list, main dex capacity exceeded
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:548)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
        at com.android.dx.command.dexer.Main.runDx(Main.java:289)
        at com.android.dx.command.dexer.Main.main(Main.java:247)
        at com.android.dx.command.Main.main(Main.java:94)
```
Even though android has been configured with the following options, which does work with the previous version of the javafxmobile plugin:
```
dexOptions {
    additionalParameters = ['--minimal-main-dex']
    keepRuntimeAnnotatedClasses = false
    javaMaxHeapSize = '4g'
}
```

**Comment by tiainen** [comment]
The problem is that version 1.x of the javafxmobile plugin added the options `additionalParameters` and  `keepRuntimeAnnotatedClasses` by extending the android DexOptions class of android gradle plugin version 1.1.3. However, these options were added in a later version of the android DexOptions. This means that we no longer need the custom DexOptions class.
