### ISSUE TITLE
v2.0.20 : Hang when deploying to iOS on latest versions of everything

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#56]
org.javafxports:jfxmobile-plugin:2.0.20
OSX 10.13.4
XCode Version 9.3 (9E145)
iOS 11.3.0 and 11.3.1 on iPad and iPhone
downConfig 3.8.0

Unable to deploy and run any app successfully.

One app that previously worked fine now hangs when the following message appears:
`lockdown asked, answer = jnr.ffi.provider.BoundedMemoryIO[address=0x138bfa8d0 size=8]`
I've tried this on multiple machines.

Another (Single View Project on Gluon) fails with a black screen and the following:
```
EXCEPtion in clinit for class com/gluonhq/charm/glisten/control/AppBar: 0x1150f9e10
Exception in Application start method
QuantumRenderer: shutdown
DONE DONE DONE
[JVDBG] VM started
```

These applications work fine on the desktop and on Android.

**Comment by odbuser2** [comment]
Please help or point me to a simple project that runs successfully on iOS with the latest versions listed above.  This is a blocker.

**Comment by odbuser2** [comment]
I think this was caused by a mismatch between the CFBundleIdentifier in the Default-info.plist and the CFBundleIdentifier specified in the small application initially deployed via XCode.  The logging did not indicate that there was a problem but eventually the small application would launch instead of the one I was trying to deploy (no idea why...).

In the process I ran into an issue with SLF4J and/or Logback related to interfaces which I'll post separately.

**Comment by odbuser2** [comment]
org.javafxports:jfxmobile-plugin:2.0.24
OSX 10.13.5
XCode Version Version 9.4 (9F1027a)
iOS 11.40
downConfig 3.8.0

I'm having the same issue as in the op.  The launchIOS hangs for a long time on:
`lockdown asked, answer = jnr.ffi.provider.BoundedMemoryIO[address=0x138bfa8d0 size=8]`

And eventually outputs:
```
[00:28:02:265] BosonAppBuilder: Path not found, exit now 
ERROR! java.lang.RuntimeException: Path not found, exit now
java.lang.RuntimeException: Path not found, exit now
	at com.gluonhq.gvmbuild.LoggingSupport.logSevere(LoggingSupport.java:106)
	at com.gluonhq.gvmbuild.BosonAppBuilder.getAppPath(BosonAppBuilder.java:1375)
	at com.gluonhq.gvmbuild.BosonAppBuilder.access$400(BosonAppBuilder.java:28)
	at com.gluonhq.gvmbuild.BosonAppBuilder$3.run(BosonAppBuilder.java:1290)
```

And continues to hang.

**Comment by odbuser2** [comment]
**Resolved**
The the value of CFBundleExecutable in Info.plist did not match the executable name.  The CFBundleExecutable value must match the executable name that is created (the application file that is created in {gradle_project}/build/gvm/)

This defaults to the gradle project name (I think) when the ide plugin is used to create a project.  However, the Info.plist file will not be updated after refactoring the project name.

**Change Request**
Please add a check in javafxports plugin that verifies that the CFBundleExecutable value in Info.plist matches the executable that is created.  It would be best to do this early... before the compilation occurs.  It's relatively easy to add this in build.gradle but it would be better if it is in the plugin.
