### ISSUE TITLE
Font usage fails on iOS

### ISSUE THREAD

**Issue by odbuser2** [javafxports/javafxmobile-plugin#66]
**BLOCKER**

**org.javafxports:jfxmobile-plugin:2.0.24
iOS 11.40**
OSX 10.13.5
XCode Version Version 9.4 (9F1027a)
downConfig 3.8.0

**Description**
Using javafx.scene.text.Font such as calling:
`Font.getFontFamilies();`

Results in:
`non-fatal, couldn't load class named com/sun/javafx/font/t2k/T2KFactory
Exception in Application start method
QuantumRenderer: shutdown`

Is this a gvm issue with the latest iOS?  The same code was working on the previous version.

**Comment by odbuser2** [comment]
PS this is a blocker b/c it hangs the App on iOS indefinitely when calling any Font method.

**Comment by johanvos** [comment]
is this specific to 11.4?

**Comment by jperedadnr** [comment]
I've upgraded to the latest versions:
- Mac 10.13.5
- Xcode Version 9.4 (9F1027a)
- iOS 11.4 (15F79)
- Jfxmobile 2.0.25

Then I tried a simple template project, adding this line of code:
`Font.getFontNames().forEach(System.out::println);`

And it works perfectly fine, printing all the fonts available.

Of course there is this printout (it always does):

`non-fatal, couldn't load class named com/sun/javafx/font/t2k/T2KFactory` 

So there is nothing wrong with 'Font`. 

In case you find `Exception in Application start method QuantumRenderer: shutdown` it seems there is an exception in your code that somehow is shallowed and not logged. 

I'd suggest adding a `try-catch (Throwable t) { t.printStacktrace(); }` to your related code.

**Comment by odbuser2** [comment]
Will do.  It is now working on on one ipad and mac with the latest of everything but not on another with the same versions (different mac and different ipad).  I had narrowed it down to any call with Font but did not put a try catch around it.  I'll report back in the next day or so.

**Comment by odbuser2** [comment]
**Clarification**
This happening on an iPhone deployed from a Macbook Pro with everything updated (well except I haven't tried with org.javafxports:jfxmobile-plugin:2.0.25 which was just released).  If I don't put a try catch around the first call to the Font class, the application will just hang.  However, with the try catch it will continue and subsequent Font calls work.

**Application Code**
```
public void start(Stage stage) throws Exception {
    try {
        System.out.println(">Calling method on font");
        Font.getFamilies();
    } catch (Throwable t) {
        t.printStackTrace();
        System.out.println("<Failed to call method on Font");
    }
    System.out.println("Made it!");
}
```
**Output**
```
>Calling method on font
java.lang.NullPointerException
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at java.lang.Throwable.<init>(Unknown Source)
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.RuntimeException.<init>(Unknown Source)
	at java.lang.NullPointerException.<init>(Unknown Source)
	at java.io.File.<init>(Unknown Source)
	at com.sun.javafx.font.PrismFontFactory.populateFontFileNameMapGeneric(Unknown Source)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(Unknown Source)
	at com.sun.javafx.font.PrismFontFactory.getFontFamilyNames(Unknown Source)
	at com.sun.javafx.font.PrismFontLoader.getFamilies(Unknown Source)
	at javafx.scene.text.Font.getFamilies(Unknown Source)
	at com.myapp.start(Unknown Source)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at com.sun.javafx.application.LauncherImpl$$Lambda$9.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$10.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$22.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$9.run(Unknown Source)
<Failed to call method on Font
Made it!
```

**Comment by odbuser2** [comment]
Same behavior with 2.0.25.

**Comment by jperedadnr** [comment]
I've tried `Font.getFamilies()` and it works just fine for me.

I'll suggest to clean your project: 
- `build`(using `./gradlew clean`)
- `.gradle`
and try again.

And from time to time removing the  `~/.gvm` folder might help as well. You will have to run the AOT compiler again, but you will get rid of old compilations.

**Comment by odbuser2** [comment]
Yes, I've tried that a few times with the same result.

**Comment by jperedadnr** [comment]
Then I don't think `Font` nor `Font.getFamilies()` have anything to do with the issue. 
If you find `QuantumRenderer: shutdown` usually it is because a NPE that throws an exception that is somehow swallowed. Adding printouts and try-catch (Throwable t) should give you a better clue.

**Comment by jperedadnr** [comment]
By the way, the new release of the plugin (2.0.27) should print the stacktrace, maybe you can give it a try?
